module.exports = {
  apps: [
    {
      name: 'nle-backend',
      script: 'dist/index.js',
      cwd: './server',
      env: {
        NODE_ENV: 'production',
      },
      env_file: './.env',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: '~/.pm2/logs/nle-backend-error.log',
      out_file: '~/.pm2/logs/nle-backend-out.log',
      time: true,
    },
    {
      name: 'nle-frontend',
      script: 'npm',
      args: 'start',
      cwd: './frontend',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      env_file: './.env',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      error_file: '~/.pm2/logs/nle-frontend-error.log',
      out_file: '~/.pm2/logs/nle-frontend-out.log',
      time: true,
    },
  ],
};
